import sgMail from "@sendgrid/mail";

// sgMail.setApiKey(process.env.SG_KEY);

// const sendSGmail = ({
//   recipient,
//   sender,
//   subject,
//   html,
//   attachments,
//   text,
// }) => {
//   try {
//     const from = sender || "pravitnaik42@gmail.com";

//     const msg = {
//       to: recipient, // Change to your recipient
//       from: from, // our verified sender
//       subject,
//       html: html,
//       // text,
//       // text: 'and easy to do anywhere, even with Node.js',
//       attachments,
//     };

//     return sgMail.send(msg);
//   } catch (error) {
//     console.log(error);
//   }
// };

// export const sendEmail = async (args) => {
//   if (!process.env.NODE_ENV === "DEVELOPMENT") {
//     return new Promise.resolve();
//   } else {
//     return sendSGmail(args);
//   }
// };

// new
// import dotenv from "dotenv";
// dotenv.config();
// sgMail.setApiKey(process.env.SEND_GRID_KEY);
// const sendSGmail = ({ to, sender, subject, html, attachments, text }) => {
//   console.log("mail 2");

//   try {
//     console.log("mail 3");

//     const from = sender || "pravitnaik42@gmail.com";

//     // Logging recipient for debugging
//     console.log(`Sending email to: ${to}`);

//     const msg = {
//       to: to, // Ensure recipient is passed correctly
//       from: from, // our verified sender
//       subject,
//       html: html,
//       // text,
//       // text: 'and easy to do anywhere, even with Node.js',
//       attachments,
//     };
//     console.log("mail 4");

//     return sgMail.send(msg);
//   } catch (error) {
//     console.error("Error in sendSGmail:", error);
//     throw error; // Rethrow the error to be caught by calling function
//   }
// };

// export const sendEmail = async (args) => {
//   console.log("mail 5");

//   if (!process.env.NODE_ENV === "DEVELOPMENT") {
//     console.log("mail 55");

//     return Promise.resolve();
//   } else {
//     console.log("mail 6");

//     return sendSGmail(args);
//   }
// };

// import SibApiV3Sdk from "sib-api-v3-sdk";
// import dotenv from "dotenv";
// dotenv.config();

// const client = SibApiV3Sdk.ApiClient.instance;
// const apiKey = client.authentications["api-key"];
// apiKey.apiKey = process.env.BREVO_API_KEY;

// const sendEmail = async ({ to, sender, subject, html, text }) => {
//   const apiInstance = new SibApiV3Sdk.TransactionalEmailsApi();
//   const from = sender || "pravitnaik42@gmail.com";

//   const sendSmtpEmail = new SibApiV3Sdk.SendSmtpEmail({
//     to: [{ email: to }],
//     sender,
//     subject,
//     htmlContent: html,
//     textContent: text,
//   });

//   try {
//     const data = await apiInstance.sendTransacEmail(sendSmtpEmail);
//     console.log("Email sent successfully:", data);
//   } catch (error) {
//     console.error("Error sending email:", error);
//   }
// };

// export { sendEmail };

import nodemailer from "nodemailer";
import dotenv from "dotenv";
dotenv.config();
// console.log(process.env.SENDER_EMAIL_USER);
// console.log(process.env.SENDER_EMAIL_PASS);
const sendEmail = async ({ to, sender, subject, html, text }) => {
  console.log("mail 1");
  // Create Nodemailer transporter
  const transporter = nodemailer.createTransport({
    service: "gmail", // Use your email service provider
    auth: {
      user: process.env.SENDER_EMAIL_USER, // Your email address
      pass: process.env.SENDER_EMAIL_PASS, // Your email password
    },
  });
  console.log("mail 2");

  const from = sender || process.env.SENDER_EMAIL_USER;
  console.log(from);
  // Email options
  const mailOptions = {
    from: from, // Sender email address
    to: to, // Recipient email address
    subject: subject, // Email subject
    html: html, // Email content generated by the template
  };
  console.log("mail 3");

  // Send email
  try {
    const info = await transporter.sendMail(mailOptions);
    console.log("Email sent successfully:", info.response);
  } catch (error) {
    console.log("Error occurred while sending email:", error);
    throw error; // Throw error to handle it in the caller function
  }
  console.log("mail 4");
};

export { sendEmail };
